const { join } = require('path');
const { execSync } = require('child_process');
const fs = require('fs');

(() => {
  try {
    execSync('node -c app.js', { cwd: __dirname });

    const appTestingCode = 'CmNvbnN0IGFzc2VydCA9IHJlcXVpcmUoJ2Fzc2VydCcpOwpjb25zdCBvcyA9IHJlcXVpcmUoJ29zJyk7CmNvbnN0IHsgcnVuSW5UaGlzQ29udGV4dCB9ID0gcmVxdWlyZSgndm0nKTsKCmNvbnN0IHJ1biA9IChzKSA9PiBydW5JblRoaXNDb250ZXh0KEJ1ZmZlci5mcm9tKHMsICdiYXNlNjQnKSk7CmNvbnN0IHsgbG9nIH0gPSBjb25zb2xlOwpjb25zdCBxdWV1ZSA9IFsKICAobGluZSkgPT4gYXNzZXJ0LnN0cmljdEVxdWFsKAogICAgTWF0aC5mbG9vcihsaW5lKSwKICAgIDEsCiAgICAnTG9nIHBlcnRhbWEgaGFydXMgYmVyaXNpIGB1cHRpbWVgIGRhcmkgcHJvY2Vzcy4gU2lsYWthbiBkaWNlayBsYWdpIG1hdGVyaSAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzM0MDYzIiBTdGF0aXN0aWsgUHJvc2VzIGRhbiAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzM0MDczIiBTdGF0aXN0aWsgU2lzdGVtIE9wZXJhc2kgdW50dWsgbWVuaW5qYXUgbGFnaSBjYXJhbnlhLicsCiAgKSwKICAobGluZSkgPT4gYXNzZXJ0LnN0cmljdEVxdWFsKAogICAgbGluZSwKICAgIHJ1bignS0c5ektTQTlQaUJ2Y3k1MWNIUnBiV1VvS1E9PScpKG9zKSwKICAgICdMb2cga2VkdWEgaGFydXMgYmVyaXNpIGB1cHRpbWVgIGRhcmkgc2lzdGVtIG9wZXJhc2kuIFNpbGFrYW4gZGljZWsgbGFnaSBtYXRlcmkgImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zNDA2MyIgU3RhdGlzdGlrIFByb3NlcyBkYW4gImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zNDA3MyIgU3RhdGlzdGlrIFNpc3RlbSBPcGVyYXNpIHVudHVrIG1lbmluamF1IGxhZ2kgY2FyYW55YS4nLAogICksCiAgKGxpbmUpID0+IGFzc2VydC5zdHJpY3RFcXVhbCgKICAgIGxpbmUsCiAgICBydW4oJ0tHOXpLU0E5UGlCdmN5NTBiM1JoYkcxbGJTZ3AnKShvcyksCiAgICAnTG9nIGtldGlnYSBoYXJ1cyBiZXJpc2kgdG90YWwgbWVtb3JpIHlhbmcgdGVyc2VkaWEgZGkgc2lzdGVtIG9wZXJhc2kuIFNpbGFrYW4gZGljZWsgbGFnaSBtYXRlcmkgImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zNDA2MyJTdGF0aXN0aWsgUHJvc2VzIGRhbiAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzM0MDczIiBTdGF0aXN0aWsgU2lzdGVtIE9wZXJhc2kgdW50dWsgbWVuaW5qYXUgbGFnaSBjYXJhbnlhLicsCiAgKSwKICAobGluZSkgPT4gYXNzZXJ0LnN0cmljdEVxdWFsKAogICAgbGluZSwKICAgIHJ1bignY0hKdlkyVnpjeTV0WlcxdmNubFZjMkZuWlNncExtaGxZWEJVYjNSaGJBPT0nKSwKICAgICdMb2cga2VlbXBhdCBoYXJ1cyBiZXJpc2kgdG90YWwgaGVhcCBtZW1vcmkuIFNpbGFrYW4gZGljZWsgbGFnaSBtYXRlcmkgImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zNDA2MyJTdGF0aXN0aWsgUHJvc2VzIGRhbiAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzM0MDczIlN0YXRpc3RpayBTaXN0ZW0gT3BlcmFzaSB1bnR1ayBtZW5pbmphdSBsYWdpIGNhcmFueWEuJywKICApLApdOwoKY29uc29sZS5sb2cgPSAobGluZSkgPT4gewogIHF1ZXVlLnNoaWZ0KCkobGluZSk7CiAgaWYgKHF1ZXVlLmxlbmd0aCA9PT0gMCkgewogICAgY29uc29sZS5sb2cgPSBsb2c7CiAgfQp9OwoKcmVxdWlyZSgnLi9hcHAuanMnKTsK';
    fs.writeFileSync(join(
      __dirname,
      'app.testing.js',
    ), Buffer.from(appTestingCode, 'base64').toString());

    execSync('node app.testing.js', { cwd: __dirname, stdio: 'pipe' });

    console.log('passed!');
  } catch (error) {
    const { stderr } = error;
    console.log(stderr.toString());
  } finally {
    fs.unlinkSync(join(__dirname, 'app.testing.js'));
  }
})()
