const { join } = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

(() => {
  try {
    execSync('node -c app.js', { cwd: __dirname });

    const originalUserCode = fs.readFileSync(join(__dirname, 'app.js'), 'utf-8');
    const additionalCodeToTest = 'Cgpjb25zdCBhc3NlcnQgPSByZXF1aXJlKCdhc3NlcnQnKTsKCnRyeSB7CiAgY29uc3QgYnVmZmVyU2l6ZSA9IDEwMDAwMDsKICAvLyBjaGVjayB1bnNhZmVCdWZmZXIKICBhc3NlcnQuZXF1YWwodW5zYWZlQnVmZmVyIGluc3RhbmNlb2YgQnVmZmVyLCB0cnVlLCAnYHVuc2FmZUJ1ZmZlcmAgaGFydXMgbWVydXBha2FuIGluc3RhbmNlIGRhcmkgYEJ1ZmZlcmAuIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgc2VjYXJhIHVuc2FmZSBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzgzMyIgTWVuZ2Fsb2thc2lrYW4gQnVmZmVyLicpOwogIGFzc2VydC5lcXVhbCh1bnNhZmVCdWZmZXIubGVuZ3RoLCBidWZmZXJTaXplLCAnUGFuamFuZyBkYXJpIGB1bnNhZmVCdWZmZXJgIGhhcnVzIDEwMDAwMC4gU2ltYWsgY2FyYSBtZW5nYWxva2FzaWthbiBuaWxhaSBCdWZmZXIgcGFkYSBtYXRlcmk6ICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM4MzMiIE1lbmdhbG9rYXNpa2FuIEJ1ZmZlci4nKTsKICBjb25zdCBzb3J0ZWRWYWx1ZXMgPSB1bnNhZmVCdWZmZXIuc29ydCgoYSwgYikgPT4gYiAtIGEpOwogIGFzc2VydC5ub3RFcXVhbChzb3J0ZWRWYWx1ZXNbMF0sIDAsICdDYXJhIG1lbWJ1YXQgYnVmZmVyIHRpZGFrIGFtYW4gKGB1bnNhZmVCdWZmZXJgKSBtYXNpaCBzYWxhaC4gU2ltYWsgY2FyYSBtZW1idWF0IGJ1ZmZlciBzZWNhcmEgdW5zYWZlIHBhZGEgbWF0ZXJpOiAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzMzODMzIiBNZW5nYWxva2FzaWthbiBCdWZmZXIuJyk7CgogIC8vIGNoZWNrIHNhZmVCdWZmZXIKICBhc3NlcnQuZXF1YWwoc2FmZUJ1ZmZlciBpbnN0YW5jZW9mIEJ1ZmZlciwgdHJ1ZSwgJ2BzYWZlQnVmZmVyYCBoYXJ1cyBtZXJ1cGFrYW4gaW5zdGFuY2UgZGFyaSBgQnVmZmVyYC4gU2ltYWsgY2FyYSBtZW1idWF0IGJ1ZmZlciBzZWNhcmEgYHNhZmVgIHBhZGEgbWF0ZXJpOiAiaHR0cHM6Ly93d3cuZGljb2RpbmcuY29tL2FjYWRlbWllcy82MTAvdHV0b3JpYWxzLzMzODMzIiBNZW5nYWxva2FzaWthbiBCdWZmZXIuJyk7CiAgYXNzZXJ0LmVxdWFsKHNhZmVCdWZmZXIubGVuZ3RoLCBidWZmZXJTaXplLCAnUGFuamFuZyBkYXJpIGBzYWZlQnVmZmVyYCBoYXJ1cyAxMDAwMDAuJyk7CiAgY29uc3Qgc29ydGVkVmFsdWVzMiA9IHNhZmVCdWZmZXIuc29ydCgoYSwgYikgPT4gYiAtIGEpOwogIGFzc2VydC5lcXVhbChzb3J0ZWRWYWx1ZXMyWzBdLCAwLCAnQ2FyYSBtZW1idWF0IGJ1ZmZlciBhbWFuIChgc2FmZUJ1ZmZlcmApIG1hc2loIHNhbGFoLiBTaW1hayBjYXJhIG1lbmdhbG9rYXNpa2FuIG5pbGFpIEJ1ZmZlciBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzgzMyIgTWVuZ2Fsb2thc2lrYW4gQnVmZmVyLicpOwoKICAvLyBjaGVjayBzdHJpbmdCdWZmZXIKICBhc3NlcnQuZXF1YWwoc3RyaW5nQnVmZmVyIGluc3RhbmNlb2YgQnVmZmVyLCB0cnVlLCAnYHN0cmluZ0J1ZmZlcmAgaGFydXMgbWVydXBha2FuIGluc3RhbmNlIGRhcmkgYEJ1ZmZlcmAuIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgZGFyaSBuaWxhaSBzdHJpbmcgcGFkYSBtYXRlcmk6ICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM4NDMiIE1lbmd1YmFoIFN0cmluZyBtZW5qYWRpIEJ1ZmZlciBkYW4gU2ViYWxpa255YS4nKTsKICBhc3NlcnQuZXF1YWwoc3RyaW5nQnVmZmVyLnRvU3RyaW5nKCksICdEaWNvZGluZycsICdDYXJhIG1lbWJ1YXQgYHN0cmluZ0J1ZmZlcmAgbWFzaWggc2FsYWguIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgZGFyaSBuaWxhaSBzdHJpbmcgcGFkYSBtYXRlcmk6ICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM4NDMiIE1lbmd1YmFoIFN0cmluZyBtZW5qYWRpIEJ1ZmZlciBkYW4gU2ViYWxpa255YS4nKTsKfSBjYXRjaCAoZXJyb3IpIHsKICBpZiAoZXJyb3IubmFtZSA9PT0gJ0Fzc2VydGlvbkVycm9yJykgewogICAgY29uc29sZS5lcnJvcihlcnJvci5tZXNzYWdlKTsKICAgIHByb2Nlc3MuZXhpdCgxKTsKICB9IGVsc2UgewogICAgY29uc29sZS5lcnJvcihgS2FtaSBnYWdhbCBtZW5ndWppIGtvZGUgeWFuZyBrYW11IHR1bGlzLiBCZXJpa3V0IGVycm9yIHlhbmcgZGloYXNpbGthbjogJHtlcnJvci5tZXNzYWdlfVxuIFNpbWFrIGVycm9yIHRlcnNlYnV0IGRhbiBwYXN0aWthbiBrYW11IHN1ZGFoIG1lbnVsaXNrYW4ga29kZSBkZW5nYW4gYmVuYXIsIHlhIWApOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0KfQ==';
    const appJSTestCode = originalUserCode + Buffer.from(additionalCodeToTest, 'base64').toString('utf-8');

    fs.writeFileSync(join(__dirname, 'app.testing.js'), appJSTestCode);

    execSync('node app.testing.js', { cwd: __dirname, stdio: 'pipe' });
    console.log('passed!');
  } catch (error) {
    const { stderr } = error;
    console.log(stderr.toString());
  } finally {
    fs.unlinkSync(join(__dirname, 'app.testing.js'));
  }
})();
