const { join } = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

(() => {
  try {
    execSync('node -c app.js', { cwd: __dirname });

    const originalUserCode = fs.readFileSync(join(__dirname, 'app.js'), 'utf-8');
    const additionalCodeToTest = 'Ci8vIHRlc3RpbmcKCmNvbnN0IHsKICBSZWFkYWJsZTogX1JlYWRhYmxlLCBwaXBlbGluZTogX3BpcGVsaW5lLCBXcml0YWJsZTogX1dyaXRhYmxlLCBUcmFuc2Zvcm06IF9UcmFuc2Zvcm0sCn0gPSByZXF1aXJlKCdzdHJlYW0nKTsKY29uc3QgYXNzZXJ0ID0gcmVxdWlyZSgnYXNzZXJ0Jyk7Cgp0cnkgewogIGNvbnN0IF9fdHJhbnNmb3JtID0gY3JlYXRlQmFzZTY0VHJhbnNmb3JtU3RyZWFtKCk7CgogIGFzc2VydC5zdHJpY3RFcXVhbChfX3RyYW5zZm9ybSBpbnN0YW5jZW9mIF9UcmFuc2Zvcm0sIHRydWUsICdGdW5nc2kgPGNvZGU+Y3JlYXRlQmFzZTY0VHJhbnNmb3JtU3RyZWFtPC9jb2RlPiBoYXJ1cyBtZW5nZW1iYWxpa2FuIFRyYW5zZm9ybSBzdHJlYW0uIFNpbWFrIGtlbWJhbGkgY2FyYSBtZW1idWF0IDxjb2RlPlRyYW5zZm9ybTwvY29kZT4gc3RyZWFtIHBhZGEgbWF0ZXJpOiA8YSBocmVmPSJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM5MDgiPlJlYWRhYmxlLVdyaXRhYmxlIFN0cmVhbTwvYT4uJyk7CgogIGZ1bmN0aW9uIGNyZWF0ZVdyaXRlU3RyZWFtKCkgewogICAgY29uc3Qgc2luayA9IFtdOwogICAgY29uc3Qgd3JpdGFibGUgPSBuZXcgX1dyaXRhYmxlKHsKICAgICAgd3JpdGUoY2h1bmssIGVuY29kaW5nLCBjYWxsYmFjaykgewogICAgICAgIHNpbmsucHVzaChjaHVuay50b1N0cmluZygpKTsKICAgICAgICBjYWxsYmFjaygpOwogICAgICB9LAogICAgfSk7CiAgICB3cml0YWJsZS5zaW5rID0gc2luazsKICAgIHJldHVybiB3cml0YWJsZTsKICB9CgogIGNvbnN0IF9fcmVhZGFibGUgPSBfUmVhZGFibGUuZnJvbShbJ0RpY29kaW5nJywgJ0luZG9uZXNpYSddKTsKICBjb25zdCBfX3dyaXRhYmxlID0gY3JlYXRlV3JpdGVTdHJlYW0oKTsKCiAgX3BpcGVsaW5lKF9fcmVhZGFibGUsIF9fdHJhbnNmb3JtLCBfX3dyaXRhYmxlLCAoZXJyKSA9PiB7CiAgICB0cnkgewogICAgICBhc3NlcnQuZXF1YWwoZXJyLCBudWxsLCAnUHJvc2VzIHRyYW5zZm9ybWFzaSBkYXRhIG1lbmdhbGFtaSBlcnJvci4gUGVyaWtzYSBpbXBsZW1lbnRhc2kgZnVuZ3NpIGBjcmVhdGVCYXNlNjRUcmFuc2Zvcm1TdHJlYW1gLCB5YSEgSmlrYSBBbmRhIG1lbWJ1dHVoa2FuIHJlZmVyZW5zaSwgc2ltYWsga2VtYmFsaSBjYXJhIG1lbWJ1YXQgPGNvZGU+VHJhbnNmb3JtPC9jb2RlPiBzdHJlYW0gcGFkYSBtYXRlcmk6IDxhIGhyZWY9Imh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzkwOCI+UmVhZGFibGUtV3JpdGFibGUgU3RyZWFtPC9hPi4nKTsKICAgICAgYXNzZXJ0LmRlZXBTdHJpY3RFcXVhbChfX3dyaXRhYmxlLnNpbmssIFsnUkdsamIyUnBibWM9JywgJ1NXNWtiMjVsYzJsaCddLCAnUGFzdGlrYW4gc3RyZWFtIGB0cmFuc2Zvcm1gIG1lbmd1YmFoIGRhdGEgbWVuamFkaSBiYXNlNjQsIHlhIS4nKTsKICAgIH0gY2F0Y2ggKGVycm9yKSB7CiAgICAgIGNvbnNvbGUuZXJyb3IoZXJyb3IubWVzc2FnZSk7CiAgICAgIHByb2Nlc3MuZXhpdCgxKTsKICAgIH0KICB9KTsKfSBjYXRjaCAoZXJyb3IpIHsKICBjb25zb2xlLmVycm9yKGBLYW1pIGdhZ2FsIG1lbmd1amkga29kZSB5YW5nIGthbXUgdHVsaXMuIEJlcmlrdXQgZXJyb3IgeWFuZyBkaWhhc2lsa2FuOiAke2Vycm9yLm1lc3NhZ2V9IFNpbWFrIGVycm9yIHRlcnNlYnV0IGRhbiBwYXN0aWthbiBrYW11IHN1ZGFoIG1lbnVsaXNrYW4ga29kZSBkZW5nYW4gYmVuYXIsIHlhIWApOwogIHByb2Nlc3MuZXhpdCgxKTsKfQ==';
    const appJSTestCode = originalUserCode + Buffer.from(additionalCodeToTest, 'base64').toString('utf-8');

    fs.writeFileSync(join(__dirname, 'app.testing.js'), appJSTestCode);

    execSync('node app.testing.js', { cwd: __dirname, stdio: 'pipe' });

    console.log('passed!');
  } catch (error) {
    const { stderr } = error;
    console.log(stderr.toString());
  } finally {
    fs.unlinkSync(join(__dirname, 'app.testing.js'));
  }
})();
